name: gorilla_linter
description: A highly sophisticated linter for Flutter apps.
version: 0.0.3
repository: https://github.com/monkeydaichan/gorilla_linter

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=3.10.1"

dependencies:
  analyzer: ^5.13.0
  custom_lint: ^0.5.2
  custom_lint_builder: ^0.5.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
